---
- name: Configure Debian WSL2 web server
  hosts: webserver
  become: yes
  roles:
    - role: base
      tags: [base]
    - role: nginx
      tags: [nginx]
    - role: app
      tags: [app]
    - role: ssh
      tags: [ssh]
